CREATE TABLE directors(_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, nationality TEXT);
CREATE TABLE categories(_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL);
CREATE TABLE actors(_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, quantity_of_oscars INTEGER NOT NULL);
CREATE TABLE movies(_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, year INTEGER NOT NULL, director_id INTEGER NOT NULL);
CREATE TABLE movies_actors(movie_id INTEGER, actor_id INTEGER);



